<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSlec5gR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSlec5gR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSlec5gR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSlec5gR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSlec5gR\App_KernelDevDebugContainer([
    'container.build_hash' => 'Slec5gR',
    'container.build_id' => '197d3ec4',
    'container.build_time' => 1596113628,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSlec5gR');
