<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNxP1pR3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNxP1pR3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNxP1pR3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNxP1pR3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNxP1pR3\App_KernelDevDebugContainer([
    'container.build_hash' => 'NxP1pR3',
    'container.build_id' => 'ee4c8938',
    'container.build_time' => 1596547008,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNxP1pR3');
